### ISSUE TITLE
Add support for yarn.lock-file-to-readme generation

### ISSUE THREAD

**Issue by tetreault** [zeke/package-json-to-readme#18]
If I work on this feature, is it something you'd incorporate into this as a PR? If not, happy to make my own repo for it.

**Comment by zeke** [comment]
Sounds like a good candidate plugin.  See https://github.com/zeke/package-json-to-readme/issues/19 where @wmhilton outlines the plugin / github org concept.

**Comment by wmhilton** [comment]
What would it do? I didn't think yarn.lock contained metadata besides dependencies.

**Comment by tetreault** [comment]
@wmhilton yeah, you're right that was why i closed the topic. I was a bit over eager with the idea and forgot that fact :).
