### ISSUE TITLE
Remove sync-exec dependency that is causing npm audit warnings

### ISSUE THREAD

**Issue by ChrisPearce** [zeke/package-json-to-readme#31]
Running npm audit on the package results in a security warning regarding the use of sync-exec.

In Node v0.12+, the following call could be used instead:
```child_process.execSync```

See https://www.npmjs.com/advisories/310

**Comment by zeke** [comment]
Thanks! Would be willing to open a pull request for this?

**Comment by fvera87** [comment]
Hey, I had the same problem, I open a PR with the fix if you don't mind :-)
