### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by alexewerlof** [zeke/package-json-to-readme#4]
I found the link to this repo on HN. I kinda miss the reason "why" someone would need to create README from Package.json and what kind of value does this add to the project if all info can be found in the package.json file?

Also I'm wondering if the main README file of this very repo is generated using itself?

I think the [README](https://github.com/zeke/package-json-to-readme/blob/master/README.md) (no pun intended) could elaborate.

**Comment by balupton** [comment]
May want to check out https://github.com/bevry/projectz — been doing the same thing since 2013
